### ISSUE TITLE
Crashes in the RMF_handleRepeat

### ISSUE THREAD

**Issue by Ant-ON** [conor42/fast-lzma2#9]
I am use FLZMA library in the 7zip library of ZA (Android app)

I can not find the reasons of the crashes. I've made minor changes to the code. A couple of small checks. But this did not change the situation. The stack trace and modified source code are attached below.

I have not been able to reproduce the problem. In what cases the problem occurs is also not known. 
@conor42, maybe you have some ideas about this?

```
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR)

backtrace:
  #00  pc 00000000003560d4  /data/app/zarchiver/lib/arm64/libp7zip.so (RMF_handleRepeat) (SourceCode: p7zip/C/fast-lzma2/radix_mf.c:306)
  #00  pc 00000000003560d4  /data/app/zarchiver/lib/arm64/libp7zip.so (RMF_recurseListChunk_generic) (SourceCode: p7zip/C/fast-lzma2/radix_mf.c:565)
  #00  pc 00000000003560d4  /data/app/zarchiver/lib/arm64/libp7zip.so (RMF_recurseListChunk) (SourceCode: p7zip/C/fast-lzma2/radix_mf.c:673)
  #00  pc 00000000003581d0  /data/app/zarchiver/lib/arm64/libp7zip.so (RMF_recurseListsBuffered) (SourceCode: p7zip/C/fast-lzma2/radix_engine.h:259)
  #00  pc 0000000000357494  /data/app/zarchiver/lib/arm64/libp7zip.so (RMF_bitpackBuildTable) (SourceCode: p7zip/C/fast-lzma2/radix_engine.h:978)
  #00  pc 0000000000357494  /data/app/zarchiver/lib/arm64/libp7zip.so (RMF_buildTable) (SourceCode: p7zip/C/fast-lzma2/radix_mf.c:689)
  #00  pc 0000000000346bb0  /data/app/zarchiver/lib/arm64/libp7zip.so (FL2_compressCurBlock_blocking) (SourceCode: p7zip/C/fast-lzma2/fl2_compress.c:311)
  #00  pc 00000000003466b8  /data/app/zarchiver/lib/arm64/libp7zip.so (FL2_compressCurBlock_async) (SourceCode: p7zip/C/fast-lzma2/fl2_compress.c:366)
  #00  pc 0000000000348f14  /data/app/zarchiver/lib/arm64/libp7zip.so (FL2POOL_thread) (SourceCode: p7zip/C/fast-lzma2/fl2_pool.c:79)
  #00  pc 0000000000084ce4  /system/lib64/libc.so (__pthread_start(void*)+36)
  #00  pc 000000000002344c  /system/lib64/libc.so (__start_thread+68)
```

FLZMA source [fast-lzma2.tar.gz](https://github.com/conor42/fast-lzma2/files/8158812/fast-lzma2.tar.gz)

**Comment by conor42** [comment]
Should be fixed by the latest commit.

**Comment by mcmilk** [comment]
@conor42 - could you provide a PR für 7-Zip ZS?
Or should I pull it in myself?

And, easy going - no need to hurry ;)

**Comment by dinhngtu** [comment]
> Should be fixed by the latest commit.

It still won't fix the main problem, which is RMF_handleRepeat not bounding reads to block_end:

```
Compress crash to crash.lzma2:
=================================================================
==1256==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x7f90293f1800 at pc 0x7f902d7f0acd bp 0x7fffd52aeb20 sp 0x7fffd52aeb10
READ of size 1 at 0x7f90293f1800 thread T0
    #0 0x7f902d7f0acc in RMF_handleRepeat radix_mf.c:303
    #1 0x7f902d7f8b3f in RMF_recurseListChunk_generic radix_mf.c:611
    #2 0x7f902d7f8b3f in RMF_recurseListChunk radix_mf.c:670
    #3 0x7f902d81ac31 in RMF_recurseListsBuffered radix_engine.h:259
    #4 0x7f902d822183 in RMF_bitpackBuildTable radix_engine.h:978
    #5 0x7f902d7fe5a5 in RMF_buildTable radix_mf.c:686
    #6 0x7f902d772751 in FL2_compressCurBlock_blocking fl2_compress.c:311
    #7 0x7f902d77464a in FL2_compressCurBlock fl2_compress.c:417
    #8 0x7f902d774d50 in FL2_compressStream_internal fl2_compress.c:933
    #9 0x7f902d77b895 in FL2_compressStream_internal fl2_compress.c:910
    #10 0x7f902d77b895 in FL2_compressStream_input fl2_compress.c:990
    #11 0x7f902d77b895 in FL2_compressStream fl2_compress.c:1025
    #12 0x7f902d770576 in compress_file test/file_test.c:42
    #13 0x7f902d771283 in main test/file_test.c:160
    #14 0x7f902c73a1c9 in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #15 0x7f902c73a28a in __libc_start_main_impl ../csu/libc-start.c:360
    #16 0x7f902d770164 in _start (test/file_test+0x104164) (BuildId: 1b3ab1d1526e669854dd2694e77f6bc133c42100)

0x7f90293f1800 is located 0 bytes after 16777216-byte region [0x7f90283f1800,0x7f90293f1800)
allocated by thread T0 here:
    #0 0x7f902d04c9c7 in malloc src/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0x7f902d817b6f in DICT_init dict_buffer.c:42

SUMMARY: AddressSanitizer: heap-buffer-overflow radix_mf.c:303 in RMF_handleRepeat
Shadow bytes around the buggy address:
  0x7f90293f1580: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7f90293f1600: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7f90293f1680: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7f90293f1700: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7f90293f1780: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x7f90293f1800:[fa]fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x7f90293f1880: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x7f90293f1900: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x7f90293f1980: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x7f90293f1a00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x7f90293f1a80: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==1256==ABORTING
```
